### PR TITLE
Several minor changes to get nodepad running

### PR DESCRIPTION
**Pull request by luebken**
1) Setting secret option in express / connect session
2) Using ! to escape html in jade.layout http://dailyjs.com/2011/01/03/node-tutorial-8/#comment-124915584
3) Not sure why but req.body.user didn't work
4) Logout link goes to get /session. Changed app.js accordingly.  del /sessions didn't work
5) Again: Not sure why but req.body.user didn't work
6) Again: Not sure why but req.body.d didn't work

### CODE REVIEW

**Comment by alexyoung** [comment]
'del sessions' will work if the client-side code is set up correctly, if you change your code to send a del from jQuery on the log out link I'll accept your changes and write a post about it (it used to work that way but we changed the template as part of the tutorials).

**Comment by luebken** [comment]
The decoding of arrays is broken in node: https://github.com/ry/node/issues/issue/566

**Comment by alexyoung** [comment]
Are you using Node 0.2.4?  This app is only intended to be used with Node 0.2.4

**Comment by luebken** [comment]
No using 0.3.6.
And thats what caused the problem. Anyway interesting findings. ;-)

**Comment by alexyoung** [comment]
Yeah, I better bookmark that issue

**Pull request closed without merging**
